# coding: utf-8

# flake8: noqa
"""
    Height APP API

    Unofficial Open API 3.1 specification for [Height App API](https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda). This is not affiliated with Height team.  --- # Authentication  The Height API uses API keys to authenticate requests. **You can view your API key in the Height settings under API**.  Authentication to the API is performed via the `Authorization` header. All API requests should be made over HTTPs.  i.e. Get your workspace.  ```bash curl https://api.height.app/workspace \\   -H \"Authorization: api-key secret_1234\" ```  Third-party applications must connect to the Height API using [OAuth2](https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda).   See [OAuth Apps on Height](https://www.notion.so/OAuth-Apps-on-Height-a8ebeab3f3f047e3857bd8ce60c2f640) for more information.  # Object formats  All objects have a unique `id` ([UUID v4](https://en.m.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))) and a `model` attribute to distinguish the model type.  e.g. a task object.  ```json {   \"id\": \"123e4567-e89b-12d3-a456-426655440000\",   \"model\": \"task\",   \"name\": \"Fix bug\",   \"index\": 1,   \"status\": \"backLog\",   [...] } ```  # Date formats  Every date uses the ISO format e.g.  ```js \"2019-11-07T17:00:00.000Z\" ```  # Real-time  Any change that you make to the API will be pushed to every user in real-time: i.e. creating tasks or messages.  # Rate limits  To keep incoming traffic under control and maintain a great experience for all our users, our API is behind a rate limiter. Users who send many requests in quick succession may see error responses that show up as status code 429.  Height allows up to 120 requests/min, but we have stricter limits on these endpoints:  - `POST /activities`: 60 requests/min - `POST /tasks`: 60 requests/min  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gil@beomjun.kr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.activity_object import ActivityObject
from swagger_client.models.activity_object_reactjis import ActivityObjectReactjis
from swagger_client.models.create_field_template_option_request import CreateFieldTemplateOptionRequest
from swagger_client.models.create_field_template_option_request_with_id import CreateFieldTemplateOptionRequestWithId
from swagger_client.models.create_list_request import CreateListRequest
from swagger_client.models.create_normal_list_request import CreateNormalListRequest
from swagger_client.models.create_normal_list_request_appearance import CreateNormalListRequestAppearance
from swagger_client.models.create_smart_list_request import CreateSmartListRequest
from swagger_client.models.create_task_from_task_form_request import CreateTaskFromTaskFormRequest
from swagger_client.models.create_task_from_task_form_request_answers import CreateTaskFromTaskFormRequestAnswers
from swagger_client.models.create_task_from_task_form_request_field import CreateTaskFromTaskFormRequestField
from swagger_client.models.create_task_from_task_form_request_with_id_queries import CreateTaskFromTaskFormRequestWithIdQueries
from swagger_client.models.create_task_from_task_form_request_with_id_queries_query_params import CreateTaskFromTaskFormRequestWithIdQueriesQueryParams
from swagger_client.models.create_task_request import CreateTaskRequest
from swagger_client.models.create_task_request_order_intent import CreateTaskRequestOrderIntent
from swagger_client.models.create_task_request_with_queries import CreateTaskRequestWithQueries
from swagger_client.models.create_task_request_with_queries_query_params import CreateTaskRequestWithQueriesQueryParams
from swagger_client.models.enabled_user_object import EnabledUserObject
from swagger_client.models.field_template_object import FieldTemplateObject
from swagger_client.models.field_template_object_label_sets import FieldTemplateObjectLabelSets
from swagger_client.models.field_template_object_labels import FieldTemplateObjectLabels
from swagger_client.models.figma_link_object import FigmaLinkObject
from swagger_client.models.figma_link_object_metadata import FigmaLinkObjectMetadata
from swagger_client.models.figma_link_object_metadata_document import FigmaLinkObjectMetadataDocument
from swagger_client.models.filters_object import FiltersObject
from swagger_client.models.get_task_form_request import GetTaskFormRequest
from swagger_client.models.get_task_request import GetTaskRequest
from swagger_client.models.get_task_request_with_id import GetTaskRequestWithId
from swagger_client.models.get_user_request import GetUserRequest
from swagger_client.models.group_object import GroupObject
from swagger_client.models.invited_user_object import InvitedUserObject
from swagger_client.models.link_objects import LinkObjects
from swagger_client.models.list_activities_request import ListActivitiesRequest
from swagger_client.models.list_activities_response import ListActivitiesResponse
from swagger_client.models.list_all_field_templates_response import ListAllFieldTemplatesResponse
from swagger_client.models.list_all_groups_response import ListAllGroupsResponse
from swagger_client.models.list_all_response import ListAllResponse
from swagger_client.models.list_all_security_log_events_response import ListAllSecurityLogEventsResponse
from swagger_client.models.list_all_users_response import ListAllUsersResponse
from swagger_client.models.list_object import ListObject
from swagger_client.models.list_object_appearance import ListObjectAppearance
from swagger_client.models.move_tasks_request import MoveTasksRequest
from swagger_client.models.move_tasks_request_order_intent import MoveTasksRequestOrderIntent
from swagger_client.models.notion_document_link_object import NotionDocumentLinkObject
from swagger_client.models.notion_document_link_object_metadata import NotionDocumentLinkObjectMetadata
from swagger_client.models.one_of_figma_link_object_metadata_frame import OneOfFigmaLinkObjectMetadataFrame
from swagger_client.models.one_of_figma_link_object_metadata_page import OneOfFigmaLinkObjectMetadataPage
from swagger_client.models.one_of_patch_tasks_request_patches_effects_items import OneOfPatchTasksRequestPatchesEffectsItems
from swagger_client.models.one_of_patch_tasks_response_list_items import OneOfPatchTasksResponseListItems
from swagger_client.models.one_of_search_tasks_response_list_items import OneOfSearchTasksResponseListItems
from swagger_client.models.patch_tasks_assignees_effect import PatchTasksAssigneesEffect
from swagger_client.models.patch_tasks_assignees_effect_assignees_ids import PatchTasksAssigneesEffectAssigneesIds
from swagger_client.models.patch_tasks_deleted_effect import PatchTasksDeletedEffect
from swagger_client.models.patch_tasks_description_effect import PatchTasksDescriptionEffect
from swagger_client.models.patch_tasks_description_effect_description import PatchTasksDescriptionEffectDescription
from swagger_client.models.patch_tasks_fields_effect import PatchTasksFieldsEffect
from swagger_client.models.patch_tasks_fields_effect_fields import PatchTasksFieldsEffectFields
from swagger_client.models.patch_tasks_fields_effect_fields_label import PatchTasksFieldsEffectFieldsLabel
from swagger_client.models.patch_tasks_fields_effect_fields_labels import PatchTasksFieldsEffectFieldsLabels
from swagger_client.models.patch_tasks_fields_effect_fields_labels_add import PatchTasksFieldsEffectFieldsLabelsAdd
from swagger_client.models.patch_tasks_fields_effect_fields_labels_remove import PatchTasksFieldsEffectFieldsLabelsRemove
from swagger_client.models.patch_tasks_fields_effect_fields_linked_tasks import PatchTasksFieldsEffectFieldsLinkedTasks
from swagger_client.models.patch_tasks_fields_effect_fields_linked_tasks_add import PatchTasksFieldsEffectFieldsLinkedTasksAdd
from swagger_client.models.patch_tasks_fields_effect_fields_linked_tasks_remove import PatchTasksFieldsEffectFieldsLinkedTasksRemove
from swagger_client.models.patch_tasks_fields_effect_user_ids import PatchTasksFieldsEffectUserIds
from swagger_client.models.patch_tasks_lists_effect import PatchTasksListsEffect
from swagger_client.models.patch_tasks_move_to_trash_effect import PatchTasksMoveToTrashEffect
from swagger_client.models.patch_tasks_name_effect import PatchTasksNameEffect
from swagger_client.models.patch_tasks_out_of_trash_effect import PatchTasksOutOfTrashEffect
from swagger_client.models.patch_tasks_parent_task_effect import PatchTasksParentTaskEffect
from swagger_client.models.patch_tasks_request import PatchTasksRequest
from swagger_client.models.patch_tasks_request_patches import PatchTasksRequestPatches
from swagger_client.models.patch_tasks_response import PatchTasksResponse
from swagger_client.models.patch_tasks_status_effect import PatchTasksStatusEffect
from swagger_client.models.post_message_request import PostMessageRequest
from swagger_client.models.post_message_request_with_queries import PostMessageRequestWithQueries
from swagger_client.models.post_message_request_with_queries_query_params import PostMessageRequestWithQueriesQueryParams
from swagger_client.models.search_tasks_request import SearchTasksRequest
from swagger_client.models.search_tasks_response import SearchTasksResponse
from swagger_client.models.security_log_event_object import SecurityLogEventObject
from swagger_client.models.sentry_alert_link_object import SentryAlertLinkObject
from swagger_client.models.sentry_alert_link_object_metadata import SentryAlertLinkObjectMetadata
from swagger_client.models.sentry_issue_link_object import SentryIssueLinkObject
from swagger_client.models.sentry_issue_link_object_metadata import SentryIssueLinkObjectMetadata
from swagger_client.models.sentry_issue_link_object_metadata_project import SentryIssueLinkObjectMetadataProject
from swagger_client.models.task_form_object import TaskFormObject
from swagger_client.models.task_form_object_questions import TaskFormObjectQuestions
from swagger_client.models.task_object import TaskObject
from swagger_client.models.task_object_fields import TaskObjectFields
from swagger_client.models.task_object_linked_tasks import TaskObjectLinkedTasks
from swagger_client.models.update_field_template_option_request import UpdateFieldTemplateOptionRequest
from swagger_client.models.update_field_template_option_request_with_id import UpdateFieldTemplateOptionRequestWithId
from swagger_client.models.update_list_request import UpdateListRequest
from swagger_client.models.update_list_request_appearance import UpdateListRequestAppearance
from swagger_client.models.update_list_request_with_id import UpdateListRequestWithId
from swagger_client.models.update_task_request import UpdateTaskRequest
from swagger_client.models.update_task_request_with_id import UpdateTaskRequestWithId
from swagger_client.models.user_object import UserObject
from swagger_client.models.workspace_object import WorkspaceObject
from swagger_client.models.zendesk_ticket_link_object import ZendeskTicketLinkObject
from swagger_client.models.zendesk_ticket_link_object_metadata import ZendeskTicketLinkObjectMetadata
