# coding: utf-8

"""
    Height APP API

    Unofficial Open API 3.1 specification for [Height App API](https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda). This is not affiliated with Height team.  --- # Authentication  The Height API uses API keys to authenticate requests. **You can view your API key in the Height settings under API**.  Authentication to the API is performed via the `Authorization` header. All API requests should be made over HTTPs.  i.e. Get your workspace.  ```bash curl https://api.height.app/workspace \\   -H \"Authorization: api-key secret_1234\" ```  Third-party applications must connect to the Height API using [OAuth2](https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda).   See [OAuth Apps on Height](https://www.notion.so/OAuth-Apps-on-Height-a8ebeab3f3f047e3857bd8ce60c2f640) for more information.  # Object formats  All objects have a unique `id` ([UUID v4](https://en.m.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))) and a `model` attribute to distinguish the model type.  e.g. a task object.  ```json {   \"id\": \"123e4567-e89b-12d3-a456-426655440000\",   \"model\": \"task\",   \"name\": \"Fix bug\",   \"index\": 1,   \"status\": \"backLog\",   [...] } ```  # Date formats  Every date uses the ISO format e.g.  ```js \"2019-11-07T17:00:00.000Z\" ```  # Real-time  Any change that you make to the API will be pushed to every user in real-time: i.e. creating tasks or messages.  # Rate limits  To keep incoming traffic under control and maintain a great experience for all our users, our API is behind a rate limiter. Users who send many requests in quick succession may see error responses that show up as status code 429.  Height allows up to 120 requests/min, but we have stricter limits on these endpoints:  - `POST /activities`: 60 requests/min - `POST /tasks`: 60 requests/min  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gil@beomjun.kr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FieldTemplateObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'model': 'str',
        'name': 'str',
        'type': 'str',
        'label_sets': 'list[FieldTemplateObjectLabelSets]',
        'labels': 'list[FieldTemplateObjectLabels]',
        'archive': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'model': 'model',
        'name': 'name',
        'type': 'type',
        'label_sets': 'labelSets',
        'labels': 'labels',
        'archive': 'archive'
    }

    def __init__(self, id=None, model=None, name=None, type=None, label_sets=None, labels=None, archive=None):  # noqa: E501
        """FieldTemplateObject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._model = None
        self._name = None
        self._type = None
        self._label_sets = None
        self._labels = None
        self._archive = None
        self.discriminator = None
        self.id = id
        self.model = model
        self.name = name
        self.type = type
        if label_sets is not None:
            self.label_sets = label_sets
        if labels is not None:
            self.labels = labels
        self.archive = archive

    @property
    def id(self):
        """Gets the id of this FieldTemplateObject.  # noqa: E501

        The unique id of the field template.  # noqa: E501

        :return: The id of this FieldTemplateObject.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FieldTemplateObject.

        The unique id of the field template.  # noqa: E501

        :param id: The id of this FieldTemplateObject.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def model(self):
        """Gets the model of this FieldTemplateObject.  # noqa: E501

        The model is always `fieldTemplate`.  # noqa: E501

        :return: The model of this FieldTemplateObject.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this FieldTemplateObject.

        The model is always `fieldTemplate`.  # noqa: E501

        :param model: The model of this FieldTemplateObject.  # noqa: E501
        :type: str
        """
        if model is None:
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501
        allowed_values = ["fieldTemplate"]  # noqa: E501
        if model not in allowed_values:
            raise ValueError(
                "Invalid value for `model` ({0}), must be one of {1}"  # noqa: E501
                .format(model, allowed_values)
            )

        self._model = model

    @property
    def name(self):
        """Gets the name of this FieldTemplateObject.  # noqa: E501

        The name of the field template.  # noqa: E501

        :return: The name of this FieldTemplateObject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FieldTemplateObject.

        The name of the field template.  # noqa: E501

        :param name: The name of this FieldTemplateObject.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this FieldTemplateObject.  # noqa: E501

        Possible types:  - `text`: any text value attribute (i.e. Story Points) - `labels`: used for tags for example - `select`: used for priority, sprint,â€¦ - `date`: used for due date,â€¦ - `linkedTasks`: usually used for dependencies and so on - `status`: the status attribute (only one field template of that type)  # noqa: E501

        :return: The type of this FieldTemplateObject.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FieldTemplateObject.

        Possible types:  - `text`: any text value attribute (i.e. Story Points) - `labels`: used for tags for example - `select`: used for priority, sprint,â€¦ - `date`: used for due date,â€¦ - `linkedTasks`: usually used for dependencies and so on - `status`: the status attribute (only one field template of that type)  # noqa: E501

        :param type: The type of this FieldTemplateObject.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["text", "labels", "select", "date", "linkedTasks", "status"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def label_sets(self):
        """Gets the label_sets of this FieldTemplateObject.  # noqa: E501

        An array of label sets, only available when the type of the field template is `status`.  # noqa: E501

        :return: The label_sets of this FieldTemplateObject.  # noqa: E501
        :rtype: list[FieldTemplateObjectLabelSets]
        """
        return self._label_sets

    @label_sets.setter
    def label_sets(self, label_sets):
        """Sets the label_sets of this FieldTemplateObject.

        An array of label sets, only available when the type of the field template is `status`.  # noqa: E501

        :param label_sets: The label_sets of this FieldTemplateObject.  # noqa: E501
        :type: list[FieldTemplateObjectLabelSets]
        """

        self._label_sets = label_sets

    @property
    def labels(self):
        """Gets the labels of this FieldTemplateObject.  # noqa: E501

        Only available when the type of the field template is `labels`, `select` or `status`.  # noqa: E501

        :return: The labels of this FieldTemplateObject.  # noqa: E501
        :rtype: list[FieldTemplateObjectLabels]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this FieldTemplateObject.

        Only available when the type of the field template is `labels`, `select` or `status`.  # noqa: E501

        :param labels: The labels of this FieldTemplateObject.  # noqa: E501
        :type: list[FieldTemplateObjectLabels]
        """

        self._labels = labels

    @property
    def archive(self):
        """Gets the archive of this FieldTemplateObject.  # noqa: E501

        This attribute has been archived.  # noqa: E501

        :return: The archive of this FieldTemplateObject.  # noqa: E501
        :rtype: bool
        """
        return self._archive

    @archive.setter
    def archive(self, archive):
        """Sets the archive of this FieldTemplateObject.

        This attribute has been archived.  # noqa: E501

        :param archive: The archive of this FieldTemplateObject.  # noqa: E501
        :type: bool
        """
        if archive is None:
            raise ValueError("Invalid value for `archive`, must not be `None`")  # noqa: E501

        self._archive = archive

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldTemplateObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldTemplateObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
