# coding: utf-8

"""
    Height APP API

    Unofficial Open API 3.1 specification for [Height App API](https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda). This is not affiliated with Height team.  --- # Authentication  The Height API uses API keys to authenticate requests. **You can view your API key in the Height settings under API**.  Authentication to the API is performed via the `Authorization` header. All API requests should be made over HTTPs.  i.e. Get your workspace.  ```bash curl https://api.height.app/workspace \\   -H \"Authorization: api-key secret_1234\" ```  Third-party applications must connect to the Height API using [OAuth2](https://www.notion.so/API-documentation-643aea5bf01742de9232e5971cb4afda).   See [OAuth Apps on Height](https://www.notion.so/OAuth-Apps-on-Height-a8ebeab3f3f047e3857bd8ce60c2f640) for more information.  # Object formats  All objects have a unique `id` ([UUID v4](https://en.m.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))) and a `model` attribute to distinguish the model type.  e.g. a task object.  ```json {   \"id\": \"123e4567-e89b-12d3-a456-426655440000\",   \"model\": \"task\",   \"name\": \"Fix bug\",   \"index\": 1,   \"status\": \"backLog\",   [...] } ```  # Date formats  Every date uses the ISO format e.g.  ```js \"2019-11-07T17:00:00.000Z\" ```  # Real-time  Any change that you make to the API will be pushed to every user in real-time: i.e. creating tasks or messages.  # Rate limits  To keep incoming traffic under control and maintain a great experience for all our users, our API is behind a rate limiter. Users who send many requests in quick succession may see error responses that show up as status code 429.  Height allows up to 120 requests/min, but we have stricter limits on these endpoints:  - `POST /activities`: 60 requests/min - `POST /tasks`: 60 requests/min  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gil@beomjun.kr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SentryAlertLinkObjectMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'organization_id': 'str',
        'last_alert_event': 'datetime',
        'alert_rule_id': 'str',
        'last_alert_status': 'str'
    }

    attribute_map = {
        'type': 'type',
        'organization_id': 'organizationId',
        'last_alert_event': 'lastAlertEvent',
        'alert_rule_id': 'alertRuleId',
        'last_alert_status': 'lastAlertStatus'
    }

    def __init__(self, type=None, organization_id=None, last_alert_event=None, alert_rule_id=None, last_alert_status=None):  # noqa: E501
        """SentryAlertLinkObjectMetadata - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._organization_id = None
        self._last_alert_event = None
        self._alert_rule_id = None
        self._last_alert_status = None
        self.discriminator = None
        self.type = type
        self.organization_id = organization_id
        self.last_alert_event = last_alert_event
        self.alert_rule_id = alert_rule_id
        self.last_alert_status = last_alert_status

    @property
    def type(self):
        """Gets the type of this SentryAlertLinkObjectMetadata.  # noqa: E501

        The type of the metadata.  # noqa: E501

        :return: The type of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SentryAlertLinkObjectMetadata.

        The type of the metadata.  # noqa: E501

        :param type: The type of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["sentryAlert"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def organization_id(self):
        """Gets the organization_id of this SentryAlertLinkObjectMetadata.  # noqa: E501

        The ID of the Sentry organization.  # noqa: E501

        :return: The organization_id of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this SentryAlertLinkObjectMetadata.

        The ID of the Sentry organization.  # noqa: E501

        :param organization_id: The organization_id of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :type: str
        """
        if organization_id is None:
            raise ValueError("Invalid value for `organization_id`, must not be `None`")  # noqa: E501

        self._organization_id = organization_id

    @property
    def last_alert_event(self):
        """Gets the last_alert_event of this SentryAlertLinkObjectMetadata.  # noqa: E501

        The date and time of the last alert event for the Sentry alert.  # noqa: E501

        :return: The last_alert_event of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :rtype: datetime
        """
        return self._last_alert_event

    @last_alert_event.setter
    def last_alert_event(self, last_alert_event):
        """Sets the last_alert_event of this SentryAlertLinkObjectMetadata.

        The date and time of the last alert event for the Sentry alert.  # noqa: E501

        :param last_alert_event: The last_alert_event of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :type: datetime
        """
        if last_alert_event is None:
            raise ValueError("Invalid value for `last_alert_event`, must not be `None`")  # noqa: E501

        self._last_alert_event = last_alert_event

    @property
    def alert_rule_id(self):
        """Gets the alert_rule_id of this SentryAlertLinkObjectMetadata.  # noqa: E501

        The ID of the alert rule for the Sentry alert.  # noqa: E501

        :return: The alert_rule_id of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :rtype: str
        """
        return self._alert_rule_id

    @alert_rule_id.setter
    def alert_rule_id(self, alert_rule_id):
        """Sets the alert_rule_id of this SentryAlertLinkObjectMetadata.

        The ID of the alert rule for the Sentry alert.  # noqa: E501

        :param alert_rule_id: The alert_rule_id of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :type: str
        """
        if alert_rule_id is None:
            raise ValueError("Invalid value for `alert_rule_id`, must not be `None`")  # noqa: E501

        self._alert_rule_id = alert_rule_id

    @property
    def last_alert_status(self):
        """Gets the last_alert_status of this SentryAlertLinkObjectMetadata.  # noqa: E501

        The status of the last alert for the Sentry alert.  # noqa: E501

        :return: The last_alert_status of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :rtype: str
        """
        return self._last_alert_status

    @last_alert_status.setter
    def last_alert_status(self, last_alert_status):
        """Sets the last_alert_status of this SentryAlertLinkObjectMetadata.

        The status of the last alert for the Sentry alert.  # noqa: E501

        :param last_alert_status: The last_alert_status of this SentryAlertLinkObjectMetadata.  # noqa: E501
        :type: str
        """
        if last_alert_status is None:
            raise ValueError("Invalid value for `last_alert_status`, must not be `None`")  # noqa: E501
        allowed_values = ["critical", "warning", "resolved"]  # noqa: E501
        if last_alert_status not in allowed_values:
            raise ValueError(
                "Invalid value for `last_alert_status` ({0}), must be one of {1}"  # noqa: E501
                .format(last_alert_status, allowed_values)
            )

        self._last_alert_status = last_alert_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SentryAlertLinkObjectMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SentryAlertLinkObjectMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
